/*
    This file was generated by a tool. Any changes made to it will be lost.
    Here all the reflected headers are included and the reflection function is generated for them
*/
#include "../reflect_me.hpp"
#include "../another_class.hpp"


void cppiReflectInit() {
  CPPI_REFLECT_AnotherClass;
  CPPI_REFLECT_GuiInputFilePath;
  CPPI_REFLECT_MyClass;

}