#pragma once


enum COLLISION_SURFACE_MATERIAL {
    COLLISION_SURFACE_NONE,
    COLLISION_SURFACE_CHAINLINK,
    COLLISION_SURFACE_CONCRETE,
    COLLISION_SURFACE_DIRT,
    COLLISION_SURFACE_DUCT,
    COLLISION_SURFACE_GRASS,
    COLLISION_SURFACE_GRAVEL,
    COLLISION_SURFACE_LADDER,
    COLLISION_SURFACE_METAL,
    COLLISION_SURFACE_METALGRATE,
    COLLISION_SURFACE_MUD,
    COLLISION_SURFACE_SAND,
    COLLISION_SURFACE_SLOSH,
    COLLISION_SURFACE_TILE,
    //COLLISION_SURFACE_WADE,
    COLLISION_SURFACE_WATER,
    COLLISION_SURFACE_WOOD,
    COLLISION_SURFACE_WOODPANEL,

    COLLISION_SURFACE_COUNT
};

struct CollisionSurfaceProp {
    COLLISION_SURFACE_MATERIAL material = COLLISION_SURFACE_NONE;
};

