#pragma once


enum class PHY_SHAPE_TYPE {
    EMPTY,
    SPHERE          = 0b000001,
    BOX             = 0b000010,
    CAPSULE         = 0b000100,
    TRIANGLE_MESH   = 0b001000,
    CONVEX_MESH     = 0b010000,
    HEIGHTFIELD     = 0b100000
};
enum class PHY_PAIR_TYPE {
    UNKNOWN,

    SPHERE_SPHERE = (int)PHY_SHAPE_TYPE::SPHERE,                                          // 0b0001

    BOX_BOX = (int)PHY_SHAPE_TYPE::BOX,                                                   // 0b0010
    SPHERE_BOX = (int)PHY_SHAPE_TYPE::SPHERE | (int)PHY_SHAPE_TYPE::BOX,            // 0b0011

    CAPSULE_CAPSULE = (int)PHY_SHAPE_TYPE::CAPSULE,                                       // 0b0100
    CAPSULE_SPHERE = (int)PHY_SHAPE_TYPE::CAPSULE | (int)PHY_SHAPE_TYPE::SPHERE,    // 0b0101
    CAPSULE_BOX = (int)PHY_SHAPE_TYPE::CAPSULE | (int)PHY_SHAPE_TYPE::BOX,          // 0b0110

    SPHERE_TRIANGLEMESH = (int)PHY_SHAPE_TYPE::SPHERE | (int)PHY_SHAPE_TYPE::TRIANGLE_MESH, // 0b1001
    BOX_TRIANGLEMESH = (int)PHY_SHAPE_TYPE::BOX | (int)PHY_SHAPE_TYPE::TRIANGLE_MESH, // 0b1010
    CAPSULE_TRIANGLEMESH = (int)PHY_SHAPE_TYPE::CAPSULE | (int)PHY_SHAPE_TYPE::TRIANGLE_MESH, // 0b1100

    SPHERE_CONVEX_MESH = (int)PHY_SHAPE_TYPE::SPHERE | (int)PHY_SHAPE_TYPE::CONVEX_MESH,
    BOX_CONVEX_MESH = (int)PHY_SHAPE_TYPE::BOX | (int)PHY_SHAPE_TYPE::CONVEX_MESH,
    CAPSULE_CONVEX_MESH = (int)PHY_SHAPE_TYPE::CAPSULE | (int)PHY_SHAPE_TYPE::CONVEX_MESH,
    TRIANGLE_MESH_CONVEX_MESH = (int)PHY_SHAPE_TYPE::TRIANGLE_MESH | (int)PHY_SHAPE_TYPE::CONVEX_MESH,
    CONVEX_MESH_CONVEX_MESH = (int)PHY_SHAPE_TYPE::CONVEX_MESH,

    SPHERE_HEIGHTFIELD = int(PHY_SHAPE_TYPE::SPHERE) | int(PHY_SHAPE_TYPE::HEIGHTFIELD),
    BOX_HEIGHTFIELD = int(PHY_SHAPE_TYPE::BOX) | int(PHY_SHAPE_TYPE::HEIGHTFIELD),
    CAPSULE_HEIGHTFIELD = int(PHY_SHAPE_TYPE::CAPSULE) | int(PHY_SHAPE_TYPE::HEIGHTFIELD),
    TRIANGLE_MESH_HEIGHTFIELD = int(PHY_SHAPE_TYPE::TRIANGLE_MESH) | int(PHY_SHAPE_TYPE::HEIGHTFIELD),
    CONVEX_MESH_HEIGHTFIELD = int(PHY_SHAPE_TYPE::CONVEX_MESH) | int(PHY_SHAPE_TYPE::HEIGHTFIELD),
    HEIGHTFIELD_HEIGHTFIELD = int(PHY_SHAPE_TYPE::HEIGHTFIELD),
};

enum class PHY_COLLIDER_TYPE {
    COLLIDER,
    PROBE
};

enum PHY_COLLIDER_FLAGS {
    COLLIDER_STATIC = 1,
    COLLIDER_NO_RESPONSE = 2,
};

