/*
    This header file was generated by a tool. Any changes made to it will be lost
*/
#pragma once




#define CPPI_REFLECT_AnotherClass \
    type_register<AnotherClass>("AnotherClass"); \
		


#define CPPI_CLASS_ANIM_SAMPLE_AnotherClass \
	struct AnotherClass_AnimSample { \
		}; \
