/*
    This file was generated by a tool. Any changes made to it will be lost.
    Here all the reflected headers are included and the reflection function is generated for them
*/
#include "reflect_me.hpp"
#include "another_class.hpp"


const char* to_string(INPUT_DEVICE e) {
	switch(e) {
	case INPUT_DEVICE::INPUT_KEYBOARD: return "INPUT_KEYBOARD";
	case INPUT_DEVICE::INPUT_PS: return "INPUT_PS";
	case INPUT_DEVICE::INPUT_XBOX: return "INPUT_XBOX";
	
	default: return "";
	}
}


void cppiReflectInit() {
  CPPI_REFLECT_AnotherClass;
  CPPI_REFLECT_Foo;
  CPPI_REFLECT_GuiInputFilePath;
  CPPI_REFLECT_MyBase;
  CPPI_REFLECT_MyClass;
  CPPI_REFLECT_MyClass__Data;

}