/*
    This file was generated by a tool. Any changes made to it will be lost.
    Here all the reflected headers are included and the reflection function is generated for them
*/

#include "reflection/reflection.hpp"
#include "../../../src/main/game/missile/missile.hpp"
#include "../../../src/main/game/game_test.hpp"


const char* to_string(TestEnum e) {
	switch(e) {
	case TestEnum::Bar: return "Bar";
	case TestEnum::Foo: return "Foo";
	case TestEnum::HelloWorld: return "HelloWorld";
	case TestEnum::Unknown: return "Unknown";
	
	default: return "";
	}
}


void cppiReflectInit() {
  CPPI_REFLECT_GameTest;
  CPPI_REFLECT_MissileActor;

}