/*
    This header file was generated by a tool. Any changes made to it will be lost
*/
#pragma once


#define CPPI_REFLECT_GuiInputFilePath \
    type_register<GuiInputFilePath>("GuiInputFilePath"); \
        

#define CPPI_REFLECT_MyClass \
    type_register<MyClass>("MyClass"); \
        

