/*
    This header file was generated by a tool. Any changes made to it will be lost
*/
#pragma once

enum INPUT_DEVICE;
const char* to_string(INPUT_DEVICE e);



#define CPPI_REFLECT_CTest \
    type_register<CTest>("CTest") \
		.parent<Tpl>() \
		
#define CPPI_REFLECT_GuiInputFilePath \
    type_register<GuiInputFilePath>("GuiInputFilePath"); \
		


#define CPPI_CLASS_ANIM_SAMPLE_CTest \
	struct CTest_AnimSample { \
		}; \

#define CPPI_CLASS_ANIM_SAMPLE_GuiInputFilePath \
	struct GuiInputFilePath_AnimSample { \
		}; \
